services:
  # client:
  #   container_name: reinhabit_dev_client
  #   build: ./client
  #   image: reinhabit_client
  #   ports: 
  #     - 8080:8080
  #   working_dir: /code
  #   volumes:
  #     - type: bind
  #       source: ./client
  #       target: /code
  #   command: [ "http-server" ]
  api:
    container_name: reinhabit_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=reinhabitUser
      - PGHOST=db
      - PGPASSWORD=reinhabitpass
      - PGDATABASE=reinhabit
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: reinhabit_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=reinhabit
      - POSTGRES_USER=reinhabitUser
      - POSTGRES_PASSWORD=reinhabitpass
volumes:
  dbdata:
networks: 
  default:
    name: reinhabit_api
