services:
  api:
    container_name: reinhabit_api
    environment: 
      - PGUSER=reinhabit
      - PGHOST=db
      - PGPASSWORD=reinhabitpass
      - PGDATABASE=reinhabit_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: reinhabit_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=reinhabit_test
      - POSTGRES_PASSWORD=reinhabitpass
volumes:
  test_db:
networks: 
  default:
    name: debug_test
